import type { Metadata } from "next";
import Link from "next/link";
import { Clock, ChevronRight, BookOpen, BarChart3, ArrowRightLeft, TrendingUp } from "lucide-react";

export const metadata: Metadata = {
  title: "Financial Statements | Models & Frameworks",
  description:
    "Master the three core financial statements: the Income Statement, Balance Sheet, and Cash Flow Statement. Learn how they connect to tell a company's full financial story.",
};

/* ─── Worked example values (fictional company: AcmeCo, FY2024) ─────────── */
const IS = {
  revenue:    "500.0",
  cogs:       "(300.0)",
  grossProfit:"200.0",
  opex:       "(60.0)",
  ebitda:     "140.0",
  da:         "(20.0)",
  ebit:       "120.0",
  interest:   "(10.0)",
  ebt:        "110.0",
  tax:        "(33.0)",
  netIncome:  "77.0",
};

const BS = {
  cash:           "50.0",
  ar:             "75.0",
  inventory:      "100.0",
  totalCA:        "225.0",
  ppe:            "200.0",
  totalAssets:    "425.0",
  ap:             "60.0",
  stDebt:         "30.0",
  totalCL:        "90.0",
  ltDebt:         "150.0",
  totalLiab:      "240.0",
  commonStock:    "50.0",
  retainedEarnings:"135.0",
  totalEquity:    "185.0",
  totalLE:        "425.0",
};

const CF = {
  netIncome:  "77.0",
  da:         "20.0",
  dnwc:       "(15.0)",
  cfo:        "82.0",
  capex:      "(30.0)",
  cfi:        "(30.0)",
  debtRepaid: "(10.0)",
  cff:        "(10.0)",
  netChange:  "42.0",
  beginCash:  "8.0",
  endCash:    "50.0",
};

const KEY_TERMS = [
  { term: "Revenue",              def: "Total income generated from selling goods or services, before any costs are deducted. Also known as the top line." },
  { term: "COGS",                 def: "Cost of Goods Sold: the direct costs of producing the goods or services sold, including materials and direct labour. Gross Profit equals Revenue minus COGS." },
  { term: "Gross Profit",         def: "Revenue minus COGS. Shows how much remains to cover overhead and generate profit after production costs are accounted for." },
  { term: "EBITDA",               def: "Earnings Before Interest, Tax, Depreciation and Amortisation. A measure of operating profitability and a proxy for cash earnings, widely used for peer comparisons." },
  { term: "Net Income",           def: "The bottom line: total profit remaining after all costs, interest, and taxes. This figure flows into Retained Earnings on the Balance Sheet each period." },
  { term: "Assets",               def: "Everything the company owns that has economic value, including cash, inventory, equipment, and intellectual property. Total Assets always equals Liabilities plus Equity." },
  { term: "Liabilities",          def: "All amounts the company owes to external parties, including accounts payable, loans, and bonds. Liabilities represent creditor claims on the company's assets." },
  { term: "Shareholders' Equity", def: "The owners' residual claim on the company's assets after all liabilities have been settled. Calculated as Assets minus Liabilities." },
  { term: "Retained Earnings",    def: "The cumulative total of net income kept in the business rather than paid out as dividends. This is the key link between the Income Statement and the Balance Sheet." },
  { term: "Operating Cash Flow",  def: "The actual cash generated by the core business in the period. Calculated by starting with Net Income, adding back non-cash charges like D&A, and adjusting for working capital movements." },
  { term: "Working Capital",      def: "Current Assets minus Current Liabilities. Measures short-term liquidity and whether the business can meet its near-term financial obligations." },
  { term: "Free Cash Flow",       def: "Operating Cash Flow minus Capital Expenditures. The cash remaining after maintaining and investing in the asset base, available to return to investors or repay debt." },
];

const STATEMENTS: Array<{
  num: string;
  title: string;
  subtitle: string;
  body: string;
  formulaHtml: string;
  vars: Array<{ symHtml: string; def: string }>;
}> = [
  {
    num: "01",
    title: "Income Statement",
    subtitle: "Profitability over a period",
    body: "The Income Statement (also called the P&L) shows how much money a company earned and spent over a specific period, either a quarter or a full year. It starts at Revenue, subtracts costs in layers, and ends at Net Income. Each deduction layer tells you something different about operational efficiency.",
    formulaHtml: "Gross Profit  = Revenue − COGS\nEBITDA        = Gross Profit − Operating Expenses\nEBIT          = EBITDA − D&amp;A\nNet Income    = EBIT − Interest − Tax",
    vars: [
      { symHtml: "Revenue",       def: "Total sales before any deductions" },
      { symHtml: "COGS",          def: "Direct production costs" },
      { symHtml: "D&amp;A",       def: "Non-cash depreciation & amortisation charge" },
      { symHtml: "EBIT",          def: "Operating profit before financing costs and tax" },
      { symHtml: "Net Income",    def: "Bottom-line profit; flows to Retained Earnings" },
    ],
  },
  {
    num: "02",
    title: "Balance Sheet",
    subtitle: "Financial position at a point in time",
    body: "The Balance Sheet is a snapshot of what a company owns (Assets) and owes (Liabilities), with the difference being Shareholders' Equity. It must always balance: every dollar of assets is financed by either debt or equity. Unlike the Income Statement, it captures a single moment in time rather than a period.",
    formulaHtml: "Assets          = Liabilities + Shareholders' Equity\nEquity          = Common Stock + Retained Earnings\nWorking Capital = Current Assets − Current Liabilities",
    vars: [
      { symHtml: "Current Assets",      def: "Cash, receivables, inventory — convertible within 1 year" },
      { symHtml: "PP&amp;E",            def: "Property, Plant & Equipment — long-term operating assets" },
      { symHtml: "Current Liabilities", def: "Payables and short-term debt due within 1 year" },
      { symHtml: "Retained Earnings",   def: "Accumulated net income not paid out as dividends" },
    ],
  },
  {
    num: "03",
    title: "Cash Flow Statement",
    subtitle: "Cash in and out over a period",
    body: "The Cash Flow Statement tracks the actual movement of cash through three activities: Operations (day-to-day business), Investing (buying and selling long-term assets), and Financing (debt and equity transactions). It reconciles net income to real cash, because a profitable company can still run out of cash.",
    formulaHtml: "CFO                = Net Income + D&amp;A ± ΔNWC\nFCF                = CFO − CAPEX\nNet Change in Cash = CFO + CFI + CFF",
    vars: [
      { symHtml: "CFO",   def: "Cash from Operations: core business cash generation" },
      { symHtml: "CFI",   def: "Cash from Investing: CAPEX, acquisitions, asset sales" },
      { symHtml: "CFF",   def: "Cash from Financing: debt raised/repaid, dividends, equity issuance" },
      { symHtml: "ΔNWC",  def: "Change in Net Working Capital (increase = cash outflow)" },
    ],
  },
];

const LINKAGES = [
  {
    from: "Income Statement",
    to:   "Balance Sheet",
    desc: "Net Income flows into Retained Earnings, increasing Shareholders' Equity each period.",
    color: "bg-emerald-50 border-emerald-200",
    badge: "bg-emerald-100 text-emerald-700",
  },
  {
    from: "Income Statement",
    to:   "Cash Flow Statement",
    desc: "Net Income is the starting point for the indirect-method Cash Flow from Operations.",
    color: "bg-blue-50 border-blue-200",
    badge: "bg-blue-100 text-blue-700",
  },
  {
    from: "Cash Flow Statement",
    to:   "Balance Sheet",
    desc: "Ending Cash on the CFS must equal the Cash balance on the Balance Sheet for the same date.",
    color: "bg-amber-50 border-amber-200",
    badge: "bg-amber-100 text-amber-700",
  },
  {
    from: "Balance Sheet",
    to:   "Cash Flow Statement",
    desc: "Changes in Balance Sheet working capital items (AR, inventory, AP) drive the ΔNWC adjustment in CFO.",
    color: "bg-purple-50 border-purple-200",
    badge: "bg-purple-100 text-purple-700",
  },
];

const TOC = [
  { href: "#what-is-fs",       label: "What are Financial Statements?" },
  { href: "#key-terms",        label: "Key Terms" },
  { href: "#three-statements", label: "The 3 Statements" },
  { href: "#worked-example",   label: "Worked Example" },
  { href: "#how-they-link",    label: "How They Link" },
  { href: "#tips",             label: "Tips" },
];

/* ─── Page ───────────────────────────────────────────────────────────────── */

export default function FinancialStatementsPage() {
  return (
    <div className="pt-16">

      {/* ── Hero ── */}
      <div className="bg-cfn-navy py-14">
        <div className="section-container max-w-[1100px] mx-auto">
          {/* Breadcrumb */}
          <nav className="flex items-center gap-1.5 text-cfn-cream/50 text-sm mb-6">
            <Link href="/" className="hover:text-cfn-cream transition-colors">Home</Link>
            <ChevronRight className="w-3.5 h-3.5" />
            <Link href="/models-frameworks" className="hover:text-cfn-cream transition-colors">Models &amp; Frameworks</Link>
            <ChevronRight className="w-3.5 h-3.5" />
            <span className="text-cfn-blue-text">Financial Statements</span>
          </nav>

          <div className="flex flex-wrap items-start gap-3 mb-4">
            <span className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-cfn-navy-100 text-cfn-navy">
              Accounting
            </span>
            <span className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1 rounded-full bg-cfn-navy-100 text-cfn-navy">
              Beginner
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-cfn-cream leading-tight mb-4">
            Financial Statements
          </h1>
          <p className="text-cfn-cream/70 text-lg max-w-2xl leading-relaxed mb-6">
            Learn to read the three core financial statements that every analyst, investor, and executive
            relies on, then see how they connect into one coherent financial picture.
          </p>
          <div className="flex flex-wrap items-center gap-5 text-cfn-cream/50 text-sm">
            <span className="flex items-center gap-1.5"><Clock className="w-4 h-4" />~12 min read</span>
            <span className="flex items-center gap-1.5"><BookOpen className="w-4 h-4" />3 statements</span>
            <span className="flex items-center gap-1.5"><TrendingUp className="w-4 h-4" />Full worked example</span>
          </div>
        </div>
      </div>

      {/* ── Body: main content + sidebar ── */}
      <div className="section-container max-w-[1100px] mx-auto py-12">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-10 items-start">

          {/* ══ Main column ══ */}
          <div className="space-y-16 min-w-0">

            {/* Section 1 — What are Financial Statements */}
            <section id="what-is-fs">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-1 h-10 bg-cfn-navy-100 rounded-full flex-shrink-0" />
                <h2 className="text-2xl sm:text-3xl font-black text-cfn-navy">
                  What are Financial Statements &amp; Why Do They Matter?
                </h2>
              </div>

              <div className="space-y-4 text-cfn-charcoal leading-relaxed mb-8">
                <p>
                  Financial statements are the standardised reports every public company produces each quarter
                  and year. They translate every business decision, from hiring and pricing to investing and
                  borrowing, into numbers that can be compared across companies, industries, and time.
                </p>
                <p>
                  There are three core statements. Each answers a different question: the Income Statement
                  asks &ldquo;how profitable was the business?&rdquo;, the Balance Sheet asks &ldquo;what
                  does the business own and owe right now?&rdquo;, and the Cash Flow Statement asks
                  &ldquo;where did the cash actually go?&rdquo;. Together, they tell the full story.
                </p>
                <p>
                  Every valuation model, from DCF and comps to LBO, is built on top of these three statements.
                  Understanding them is the single most important foundational skill in finance.
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {[
                  { Icon: BarChart3,      title: "Equity Research",   body: "Analysts build earnings models by forecasting all three statements forward 2–3 years to arrive at a target price." },
                  { Icon: ArrowRightLeft, title: "Credit Analysis",   body: "Lenders study the Balance Sheet (leverage) and Cash Flow Statement (coverage ratios) to assess repayment risk." },
                  { Icon: TrendingUp,     title: "Investment Banking", body: "M&A and IPO due diligence starts with normalising historical financials to build a clean model and assess deal economics." },
                ].map(({ Icon, title, body }) => (
                  <div key={title} className="bg-cfn-cream rounded-2xl p-5 border border-cfn-navy-100 shadow-card">
                    <div className="w-10 h-10 rounded-xl bg-cfn-cream/10 flex items-center justify-center mb-3">
                      <Icon className="w-5 h-5 text-cfn-mid" />
                    </div>
                    <h3 className="font-bold text-cfn-navy mb-1">{title}</h3>
                    <p className="text-sm text-cfn-muted leading-relaxed">{body}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Section 2 — Key Terms */}
            <section id="key-terms">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-1 h-10 bg-cfn-navy-100 rounded-full flex-shrink-0" />
                <h2 className="text-2xl sm:text-3xl font-black text-cfn-navy">
                  Key Terms Explained
                </h2>
              </div>
              <p className="text-cfn-charcoal leading-relaxed mb-6">
                Before reading a financial statement, make sure you understand what each line item actually means.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {KEY_TERMS.map(({ term, def }) => (
                  <div key={term} className="bg-cfn-cream rounded-xl p-5 border border-cfn-navy-100 shadow-card">
                    <p className="text-xs font-bold text-cfn-mid font-mono uppercase tracking-wider mb-2">{term}</p>
                    <p className="text-sm text-cfn-muted leading-relaxed">{def}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Section 3 — The 3 Statements */}
            <section id="three-statements">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-1 h-10 bg-cfn-navy-100 rounded-full flex-shrink-0" />
                <h2 className="text-2xl sm:text-3xl font-black text-cfn-navy">
                  The 3 Core Statements
                </h2>
              </div>
              <p className="text-cfn-charcoal leading-relaxed mb-8">
                Each statement serves a distinct purpose. Analysts read all three together — no single statement
                tells the full story on its own.
              </p>
              <div className="space-y-6">
                {STATEMENTS.map(({ num, title, subtitle, body, formulaHtml, vars }) => (
                  <div key={num} className="flex gap-5">
                    {/* Number badge */}
                    <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-cfn-navy flex items-center justify-center">
                      <span className="text-cfn-blue-text font-black text-sm">{num}</span>
                    </div>
                    {/* Content */}
                    <div className="flex-1 min-w-0">
                      <h3 className="font-bold text-cfn-navy text-lg mb-0.5">{title}</h3>
                      <p className="text-xs font-semibold text-cfn-mid uppercase tracking-wider mb-2">{subtitle}</p>
                      <p className="text-cfn-charcoal text-sm leading-relaxed mb-3">{body}</p>

                      {/* Formula block */}
                      <pre
                        className="bg-cfn-navy-800 text-cfn-blue-text text-xs font-mono px-4 py-3 rounded-xl overflow-x-auto leading-6 whitespace-pre-wrap"
                        dangerouslySetInnerHTML={{ __html: formulaHtml }}
                      />

                      {/* Variable legend */}
                      {vars.length > 0 && (
                        <dl className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1.5">
                          {vars.map(({ symHtml, def }, i) => (
                            <div key={i} className="flex items-baseline gap-2 text-xs">
                              <dt
                                className="font-mono font-bold text-cfn-navy flex-shrink-0"
                                dangerouslySetInnerHTML={{ __html: symHtml }}
                              />
                              <dd className="text-cfn-muted">{def}</dd>
                            </div>
                          ))}
                        </dl>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Section 4 — Worked Example */}
            <section id="worked-example">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-1 h-10 bg-cfn-navy-100 rounded-full flex-shrink-0" />
                <h2 className="text-2xl sm:text-3xl font-black text-cfn-navy">
                  Worked Example
                </h2>
              </div>
              <p className="text-cfn-charcoal leading-relaxed mb-2">
                AcmeCo — a fictional mid-size manufacturer. All figures in $M (FY2024).
                Notice how Net Income appears in both the Income Statement and Cash Flow Statement,
                and Ending Cash ties back to the Balance Sheet.
              </p>
              <p className="text-cfn-muted text-sm mb-8">All figures in $M unless noted.</p>

              <div className="space-y-8">

                {/* ── Income Statement ── */}
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest text-cfn-mid mb-3">Income Statement (FY2024)</p>
                  <div className="bg-cfn-cream rounded-2xl border border-cfn-navy-100 shadow-card overflow-hidden">
                    <div className="overflow-x-auto">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="bg-cfn-navy text-cfn-cream">
                            <th className="text-left px-4 py-3 font-semibold">Income Statement Item</th>
                            <th className="text-right px-4 py-3 font-semibold">FY2024 ($M)</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-cfn-navy-100 font-mono">
                          <tr>
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">Revenue</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{IS.revenue}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">− Cost of Goods Sold</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{IS.cogs}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">= Gross Profit</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{IS.grossProfit}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">− Operating Expenses</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{IS.opex}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">= EBITDA</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{IS.ebitda}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">− Depreciation &amp; Amortisation</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{IS.da}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">= EBIT</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{IS.ebit}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">− Interest Expense</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{IS.interest}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy">= EBT</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{IS.ebt}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">− Income Tax (30%)</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{IS.tax}</td>
                          </tr>
                          <tr className="bg-cfn-navy font-black">
                            <td className="px-4 py-4 font-sans text-cfn-cream">= Net Income</td>
                            <td className="px-4 py-4 text-right text-cfn-cream text-base">{IS.netIncome}</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>

                {/* ── Balance Sheet ── */}
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest text-cfn-mid mb-3">Balance Sheet (as at Dec 31, 2024)</p>
                  <div className="bg-cfn-cream rounded-2xl border border-cfn-navy-100 shadow-card overflow-hidden">
                    <div className="overflow-x-auto">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="bg-cfn-navy text-cfn-cream">
                            <th className="text-left px-4 py-3 font-semibold">Balance Sheet Item</th>
                            <th className="text-right px-4 py-3 font-semibold">$M</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-cfn-navy-100 font-mono">
                          {/* Assets */}
                          <tr className="bg-cfn-navy/5">
                            <td colSpan={2} className="px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cfn-navy font-sans">Assets</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Cash &amp; Equivalents</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.cash}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Accounts Receivable</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.ar}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Inventory</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.inventory}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">Total Current Assets</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{BS.totalCA}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">PP&amp;E (net)</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.ppe}</td>
                          </tr>
                          <tr className="bg-cfn-navy font-bold">
                            <td className="px-4 py-3 font-sans text-cfn-cream">Total Assets</td>
                            <td className="px-4 py-3 text-right text-cfn-cream font-black">{BS.totalAssets}</td>
                          </tr>
                          {/* Liabilities */}
                          <tr className="bg-cfn-navy/5">
                            <td colSpan={2} className="px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cfn-navy font-sans">Liabilities</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Accounts Payable</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.ap}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Short-term Debt</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.stDebt}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">Total Current Liabilities</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{BS.totalCL}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Long-term Debt</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.ltDebt}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">Total Liabilities</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{BS.totalLiab}</td>
                          </tr>
                          {/* Equity */}
                          <tr className="bg-cfn-navy/5">
                            <td colSpan={2} className="px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cfn-navy font-sans">Shareholders&apos; Equity</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Common Stock</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.commonStock}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Retained Earnings</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{BS.retainedEarnings}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">Total Equity</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{BS.totalEquity}</td>
                          </tr>
                          <tr className="bg-cfn-navy font-black">
                            <td className="px-4 py-4 font-sans text-cfn-cream">Total Liabilities &amp; Equity</td>
                            <td className="px-4 py-4 text-right text-cfn-cream text-base">{BS.totalLE}</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div className="mt-3 p-4 bg-cfn-navy/5 border-l-4 border-cfn-navy rounded-r-xl">
                    <p className="text-xs text-cfn-charcoal">
                      <span className="font-bold text-cfn-navy">Check:</span> Total Assets ($425.0M) = Total Liabilities ($240.0M) + Total Equity ($185.0M). The balance sheet balances. ✓
                    </p>
                  </div>
                </div>

                {/* ── Cash Flow Statement ── */}
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest text-cfn-mid mb-3">Cash Flow Statement (FY2024)</p>
                  <div className="bg-cfn-cream rounded-2xl border border-cfn-navy-100 shadow-card overflow-hidden">
                    <div className="overflow-x-auto">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="bg-cfn-navy text-cfn-cream">
                            <th className="text-left px-4 py-3 font-semibold">Cash Flow Item</th>
                            <th className="text-right px-4 py-3 font-semibold">FY2024 ($M)</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-cfn-navy-100 font-mono">
                          {/* CFO */}
                          <tr className="bg-cfn-navy/5">
                            <td colSpan={2} className="px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cfn-navy font-sans">Operating Activities</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Net Income</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{CF.netIncome}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">+ Depreciation &amp; Amortisation</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{CF.da}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">± Change in Net Working Capital</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{CF.dnwc}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">= Cash from Operations (CFO)</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{CF.cfo}</td>
                          </tr>
                          {/* CFI */}
                          <tr className="bg-cfn-navy/5">
                            <td colSpan={2} className="px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cfn-navy font-sans">Investing Activities</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Capital Expenditures</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{CF.capex}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">= Cash from Investing (CFI)</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{CF.cfi}</td>
                          </tr>
                          {/* CFF */}
                          <tr className="bg-cfn-navy/5">
                            <td colSpan={2} className="px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cfn-navy font-sans">Financing Activities</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-navy">Debt Repaid</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{CF.debtRepaid}</td>
                          </tr>
                          <tr className="bg-cfn-navy/5">
                            <td className="px-4 py-3 font-sans text-cfn-navy font-semibold">= Cash from Financing (CFF)</td>
                            <td className="px-4 py-3 text-right text-cfn-navy font-semibold">{CF.cff}</td>
                          </tr>
                          {/* Summary */}
                          <tr>
                            <td className="px-4 py-3 font-sans text-cfn-navy">Net Change in Cash</td>
                            <td className="px-4 py-3 text-right text-cfn-navy">{CF.netChange}</td>
                          </tr>
                          <tr>
                            <td className="px-4 py-3 pl-8 font-sans text-cfn-muted text-xs">Beginning Cash</td>
                            <td className="px-4 py-3 text-right text-cfn-muted">{CF.beginCash}</td>
                          </tr>
                          <tr className="bg-cfn-navy font-black">
                            <td className="px-4 py-4 font-sans text-cfn-cream">= Ending Cash</td>
                            <td className="px-4 py-4 text-right text-cfn-cream text-base">{CF.endCash}</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div className="mt-3 p-4 bg-cfn-navy/5 border-l-4 border-cfn-navy rounded-r-xl">
                    <p className="text-xs text-cfn-charcoal">
                      <span className="font-bold text-cfn-navy">Check:</span> Ending Cash ($50.0M) matches Cash &amp; Equivalents on the Balance Sheet ($50.0M). The statements tie. ✓
                    </p>
                  </div>
                </div>

              </div>
            </section>

            {/* Section 5 — How They Link */}
            <section id="how-they-link">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-1 h-10 bg-cfn-navy-100 rounded-full flex-shrink-0" />
                <h2 className="text-2xl sm:text-3xl font-black text-cfn-navy">
                  How the 3 Statements Link
                </h2>
              </div>
              <p className="text-cfn-charcoal leading-relaxed mb-6">
                The three statements are not independent: they are deeply interconnected. In any
                well-built financial model, these four links must hold exactly. If they do not,
                the model has an error.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
                {LINKAGES.map(({ from, to, desc, color, badge }) => (
                  <div key={`${from}-${to}`} className={`rounded-2xl p-5 border ${color}`}>
                    <div className="flex items-center gap-2 mb-3">
                      <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${badge}`}>{from}</span>
                      <ArrowRightLeft className="w-3.5 h-3.5 text-cfn-muted" />
                      <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${badge}`}>{to}</span>
                    </div>
                    <p className="text-sm text-cfn-charcoal leading-relaxed">{desc}</p>
                  </div>
                ))}
              </div>

              <div className="p-5 bg-cfn-navy rounded-2xl">
                <p className="text-cfn-cream font-bold text-sm mb-2">Key insight for interviews</p>
                <p className="text-cfn-cream/80 text-sm leading-relaxed">
                  A classic interview question: &ldquo;If depreciation increases by $10M, how does that flow
                  through the three statements?&rdquo; Answer: EBIT falls by $10M → Net Income falls by $7M
                  (assuming 30% tax) → on the Cash Flow Statement, the $10M D&amp;A is added back, so CFO
                  only falls by $3M (the tax cash saved) → Cash &amp; Equivalents on the Balance Sheet falls
                  by $3M, and Retained Earnings falls by $7M. All three statements move in concert.
                </p>
              </div>
            </section>

            {/* Section 6 — Tips */}
            <section id="tips">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-1 h-10 bg-cfn-navy-100 rounded-full flex-shrink-0" />
                <h2 className="text-2xl sm:text-3xl font-black text-cfn-navy">
                  Tips for Reading Financial Statements
                </h2>
              </div>
              <p className="text-cfn-charcoal leading-relaxed mb-6">
                Once you can read the numbers, learn to read between them. Here is how experienced analysts approach a new set of financials:
              </p>
              <ul className="space-y-3">
                {[
                  "Always start with the Cash Flow Statement. It is harder to manipulate than Net Income and shows what actually happened to cash in the period.",
                  "Compare Gross Margin and EBITDA margin across periods. Margin compression is often the first warning sign of a deteriorating business.",
                  "Watch for rising Accounts Receivable as a percentage of Revenue. It may indicate the company is recording revenue it has not yet collected.",
                  "A company can be profitable but cash-flow negative if it is investing heavily in growth. That is not always a problem, but context matters.",
                  "Check that the balance sheet actually balances. In a model, this is always a check column. In real life, it always does by definition.",
                  "Retained Earnings should grow by Net Income minus Dividends each year. If it doesn't, look for share buybacks or restatements.",
                  "Read the footnotes. Revenue recognition policies, off-balance-sheet items, and related-party transactions are all disclosed there.",
                ].map((tip, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-cfn-charcoal">
                    <span className="w-5 h-5 rounded-full bg-cfn-navy-100 text-cfn-navy text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    {tip}
                  </li>
                ))}
              </ul>
            </section>

          </div>{/* end main column */}

          {/* ══ Sidebar ══ */}
          <aside className="hidden lg:block space-y-6 sticky top-24">

            {/* Table of Contents */}
            <div className="bg-cfn-cream rounded-2xl border border-cfn-navy-100 shadow-card p-5">
              <p className="text-xs font-bold uppercase tracking-widest text-cfn-mid mb-4">On This Page</p>
              <nav className="space-y-1">
                {TOC.map(({ href, label }) => (
                  <a
                    key={href}
                    href={href}
                    className="block text-sm text-cfn-muted hover:text-cfn-navy hover:translate-x-1 transition-all py-1"
                  >
                    {label}
                  </a>
                ))}
              </nav>
            </div>

            {/* Model Stats */}
            <div className="bg-cfn-navy rounded-2xl p-5 text-cfn-cream">
              <p className="text-xs font-bold uppercase tracking-widest text-cfn-blue-text mb-4">Model Stats</p>
              <dl className="space-y-3 text-sm">
                {[
                  { dt: "Category",   dd: "Accounting" },
                  { dt: "Difficulty", dd: "Beginner" },
                  { dt: "Read time",  dd: "~12 min" },
                  { dt: "Statements", dd: "3" },
                  { dt: "Key terms",  dd: "12 definitions" },
                  { dt: "Outputs",    dd: "IS, BS, CFS + linkages" },
                ].map(({ dt, dd }) => (
                  <div key={dt} className="flex justify-between gap-2">
                    <dt className="text-cfn-cream/50">{dt}</dt>
                    <dd className="font-semibold text-right">{dd}</dd>
                  </div>
                ))}
              </dl>
            </div>

            {/* Related Models */}
            <div className="bg-cfn-cream rounded-2xl border border-cfn-navy-100 shadow-card p-5">
              <p className="text-xs font-bold uppercase tracking-widest text-cfn-mid mb-4">Related Models</p>
              <div className="space-y-2">
                {[
                  { label: "DCF Valuation",     href: "/models-frameworks/dcf-valuation" },
                  { label: "Comps Analysis",     href: "/models-frameworks?category=comparable-analysis" },
                  { label: "LBO Modeling",       href: "/models-frameworks?category=lbo" },
                  { label: "Merger Model",       href: "/models-frameworks?category=merger-model" },
                ].map(({ label, href }) => (
                  <Link
                    key={label}
                    href={href}
                    className="flex items-center justify-between text-sm text-cfn-navy hover:text-cfn-navy-800 transition-colors py-1 group"
                  >
                    {label}
                    <ChevronRight className="w-3.5 h-3.5 text-cfn-muted group-hover:text-cfn-navy transition-colors" />
                  </Link>
                ))}
              </div>
            </div>

          </aside>

        </div>
      </div>
    </div>
  );
}
